apiVersion: resources.azure.upbound.io/v1beta1
kind: SubscriptionTemplateDeployment
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/subscriptiontemplatedeployment
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    testing.upbound.io/example-name: example
  name: sea-crossplane-rg
spec:
  forProvider:
    location: Southeast Asia
    templateContent: >2
       {
         "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
         "contentVersion": "1.0.0.0",
         "parameters": {},
         "variables": {},
         "resources": [
           {
             "type": "Microsoft.Resources/resourceGroups",
             "apiVersion": "2018-05-01",
             "location": "Southeast Asia",
             "name": "sea-crossplane-rg",
             "properties": {}
           }
         ]
       }
    tags:
      provisioner: crossplane
  deletionPolicy: Delete
  providerConfigRef:
    name: azure-provider
