apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-crossplane-provision
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ./azure
    repoURL: 'https://github.com/XQuyTran/gitops-crossplane'
    targetRevision: crossplane-azure-resources
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 30s
        maxDuration: 15m0s
        factor: 2