apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/cluster
    uptest.upbound.io/timeout: "2400"
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    testing.upbound.io/example-name: example
  name: crossplane-eks-cluster
spec:
  forProvider:
    region: ap-southeast-1
    roleArnRef:
      name: eks-cluster-crossplane-role
    vpcConfig:
      - subnetIdRefs:
        - name: eks-crossplane-subnet-a
        - name: eks-crossplane-subnet-b
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider