apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: crossplane-eks-ng
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    capacityType: SPOT
    clusterNameRef:
      name: crossplane-eks-cluster
    nodeRoleArnRef:
      name: eks-node-crossplane-role
    region: ap-southeast-1
    scalingConfig:
      - desiredSize: 1
        maxSize: 1
        minSize: 1
    subnetIdRefs:
      - name: eks-crossplane-subnet-a
      - name: eks-crossplane-subnet-b
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider