apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/instanceprofile
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: eks-cluster-crossplane-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Course: gitops-crossplane
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/role
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  labels:
    testing.upbound.io/example-name: role
  name: eks-cluster-attachment
spec:
  forProvider:
    roleRef:
      name: eks-cluster-crossplane-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  deletionPolicy: Delete
  providerConfigRef:
    name: aws-provider