apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: eks-crossplane-subnet-a
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    availabilityZone: ap-southeast-1a
    cidrBlock: 172.16.0.0/24
    region: ap-southeast-1
    vpcIdRef:
      name: eks-crossplane-vpc
  managementPolicies: Full
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: eks-crossplane-subnet-b
  namespace: crossplane-system
spec:
  forProvider:
    availabilityZone: ap-southeast-1b
    cidrBlock: 172.16.0.0/24
    region: ap-southeast-1
    vpcIdRef:
      name: eks-crossplane-vpc
  managementPolicies: Full
  providerConfigRef:
    name: aws-provider